### ISSUE TITLE
Add this to pub.dev?

### ISSUE THREAD

**Issue by Mayb3Nots** [billylev/flutter_zoom_pinch#2]
This is just great work. Reduced the time I needed (and hopefully more people) to spend on studying and researching to code my own. Was wondering if you would like to publish this to pub.dev? I would love to help with it.

**Comment by billylev** [comment]
Happy it helped. I have thought about doing that, but it becomes a maintenance issue. Have to keep it updated and fix bugs as flutter evolves, especially if used in projects. I might not have the time.

**Comment by Mayb3Nots** [comment]
@billylev I have added this to pub.dev thanks to you! 
https://pub.dev/packages/zoom_pinch_overlay
